### ISSUE TITLE
Portions of Mod don't work on server like Place, Mine, and Hurt

### ISSUE THREAD

**Issue by kgsbowtie** [RainbowVille/minegasm#33]
When playing the mod on a server certain portions of the mod don't work such as Place (the `onPlace` function), Mine (the `onBreak` function), and Hurt (and the `onHurt` function). These functions don't seem to fire when playing on a server, but do fire on single player. 

Mine (`onHarvest`) *does* work though, as does Attack (`onAttack`).

It seems that most things that extends `net.minecraftforge.event.entity.player` does work (`AttackEntityEvent`, `PlayerEvent`), and anything that extends anything else doesn't. Notable exceptions are: `onItemPickup` and `onHurt`.

These functions fire and work correctly in a single player world, but they do not fire and `LOGGER.info` messages do not appear in the logs when playing on a server world for those functions. 

The issue seems to be that the server is waiting on something and needs to be told it needs to send this info to the client? I'm not exactly sure. I've posed what I believe might be some useful log information below. 

```
[com.therainbowville.repack.org.eclipse.jetty.io.ChannelEndPoint/]: Key interests updated 0 -> 1 on SocketChannelEndPoint@591b6d4a{l=/127.0.0.1:49829,r=localhost/127.0.0.1:12345,OPEN,fill=FI,flush=-,to=0/300000}{io=1/1,kio=1,kro=1}->WebSocketClientConnection@6caec[s=ConnectionState@5138782d[OPENED],f=Flusher@116cd038[IDLE][queueSize=0,aggregateSize=-1,terminated=null],g=Generator[CLIENT,validating],p=Parser@3604a2d0[ExtensionStack,s=START,c=0,len=4,f=null]]
[20Jun2024 16:34:42.556] [WebSocketClient@1232502732-93/DEBUG] [com.therainbowville.repack.org.eclipse.jetty.io.ManagedSelector/]: updates 0
[20Jun2024 16:34:42.556] [WebSocketClient@1232502732-93/DEBUG] [com.therainbowville.repack.org.eclipse.jetty.io.ManagedSelector/]: Selector sun.nio.ch.KQueueSelectorImpl@164fe9b9 waiting with 1 keys
```

**Comment by RSwoop** [comment]
#34 should fix this I think
